spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/datashare
    username: datashare
    password: datashare
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# ddl-auto: update = c'est ce qui permet de configurer Spring Boot pour qu'il automatise la création de tables dans la base de données. 
# Ensuite dans le Jwt j'avais laissé le secret de JWT. Il ne faut pas, et le mettre dans .env. 

# je retrouve ici les variables d'environnement (ex = ${JWT_SECRET}) implantées dans .env. Pour sécuriser au maximum les données. 
# Aucune information ne transparait ici. 

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# ici aussi les variables d'environnement concernant Amazon (stockage)
aws:
  s3:
    bucket: ${AWS_BUCKET}
    region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

