spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/datashare
    username: datashare
    password: datashare
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: dGVzdC1zZWNyZXQtcG91ci1sZXMtdGVzdHMtdW5pcXVlbWVudA==
  expiration: 86400000

aws:
  s3:
    bucket: test-bucket
    region: eu-west-3
  credentials:
    access-key: test-access-key
    secret-key: test-secret-key